App({
  onLaunch: function () {
    this.globalData.allCatsArray = [
      this.globalData.cookie,
      this.globalData.zebra,
      this.globalData.glove,
      this.globalData.shadow,
      this.globalData.snowball,
      this.globalData.tiger,
      this.globalData.socks,
      this.globalData.fog,
      this.globalData.whiskers,
      this.globalData.dream,
      this.globalData.furball,
      this.globalData.moon,
      this.globalData.money,
      this.globalData.steamedBun,
      this.globalData.dumpling,
      this.globalData.cola,
      this.globalData.riceCooker,
      this.globalData.yolk,
      this.globalData.orange,
    ];
  },
  globalData: {
    cookie: ["/resource/cats/full-body/1.jpg", "饼干", "橘色", "母", "已绝育", "2023-05-01", "健康", "友好"],
    zebra: ["/resource/cats/full-body/2.jpg", "斑马", "白色", "公", "已绝育", "2023-06-15", "活跃", "好奇"],
    glove: ["/resource/cats/full-body/3.jpg", "手套", "黑色", "公", "已绝育", "2023-07-25", "健康", "独立"],
    shadow: ["/resource/cats/full-body/4.jpg", "影子", "白色", "母", "已绝育", "2023-08-05", "健康", "粘人"],
    snowball: ["/resource/cats/full-body/5.jpg", "雪球", "白色", "母", "未绝育", "未绝育", "活泼", "友好"],
    tiger: ["/resource/cats/full-body/6.jpg", "老虎", "虎斑", "公", "未绝育", "未绝育", "勇敢", "活泼"],
    socks: ["/resource/cats/full-body/7.jpg", "袜子", "黑色带白袜子", "公", "未绝育", "未绝育", "好奇", "好动"],
    fog: ["/resource/cats/full-body/8.jpg", "雾气", "灰色", "母", "已绝育", "2023-09-10", "安静", "温柔"],
    whiskers: ["/resource/cats/full-body/9.jpg", "胡须", "白色", "公", "已绝育", "2023-10-05", "好奇", "聪明"],
    dream: ["/resource/cats/full-body/10.jpg", "小梦", "三花色", "母", "未绝育", "未绝育", "害羞", "温柔"],
    furball: ["/resource/cats/full-body/11.jpg", "毛球", "橘色", "公", "未绝育", "未绝育", "友好", "活泼"],
    moon: ["/resource/cats/full-body/12.jpg", "月亮", "灰色", "母", "已绝育", "2023-11-20", "好奇", "安静"],
    money: ["/resource/cats/full-body/13.jpg", "钱宝", "黑色", "公", "已绝育", "2023-12-01", "勇敢", "独立"],
    steamedBun: ["/resource/cats/full-body/14.jpg", "馒头", "白色", "母", "已绝育", "2024-01-10", "健康", "粘人"],
    dumpling: ["/resource/cats/full-body/15.jpg", "汤圆", "黑色", "公", "未绝育", "未绝育", "好动", "好奇"],
    cola: ["/resource/cats/full-body/16.jpg", "可乐", "橘色", "母", "已绝育", "2024-02-01", "友好", "活泼"],
    riceCooker: ["/resource/cats/full-body/17.jpg", "电饭煲", "黑色带橘色", "公", "未绝育", "未绝育", "勇敢", "好动"],
    yolk: ["/resource/cats/full-body/18.jpg", "蛋黄", "黄色", "母", "已绝育", "2024-03-15", "温柔", "安静"],
    orange: ["/resource/cats/full-body/19.jpg", "橘子", "橘色", "公", "未绝育", "未绝育", "好奇", "活泼"],
  }
})